export default {
    title:{
        kk:"Тегін бейдждер/аккредитациялар конструкторы 5 минут ішінде!",
        ru:"Бесплатный конструктор бейджиков/аккредитации за 5 минут!",
        en:"Free badge/accreditation constructor in 5 minutes!"
    },
    description: {
        kk:"Бейдждерді жасау енді оңайырақ болды, біздің конструктордың көмегімен сіз оны тегін, қарапайым және шексіз мөлшерде жасай аласыз.",
        ru:"Создавать бейджиков стало теперь еще проще, с помощью нашего конструктора вы можете создавать его бесплатно, просто и в неограниченном количестве.",
        en:"Creating badges has now become even easier, with the help of our constructor, you can create it free, simply and in unlimited quantities."
    },
    keywords:{
        kk:"бейджик конструкторы, онлайн бейджик конструкторы, автокад бейджик конструкторы, А4 бейджик конструкторы, андроид бейджик конструкторы, бережков конструкторы, бейджик конструкторы тегін, битрикс бейджик конструкторы, Битрикс бейджик конструкторы, фоны жоқ бейджик конструкторы, Word-тағы бейджик конструкторы, Гугл бейджик конструкторы, гост бейджик конструкторы, бейджик конструкторы үшін бейджик конструкторы сайт, қызметкерлерге арналған бейдждер конструкторы, басып шығаруға арналған бейдждер конструкторы, фотошопқа арналған бейдждер конструкторы, бейджиктер конструкторы ексель, бейджик құрастырушы егов, бейджик конструкторы ескд, кірпі бейджик конструкторы, бейджик конструкторы ексель, бейджик конструкторы журнал, жж бейджик конструкторы, әйелдер бейджигі конструкторы, бейджик конструкторы, бейджик конструкторы тапсырыс беру, бейджик конструкторы ескертпелер, бейджик конструкторы заң, бейджик конструкторы Нұсқаулық, бейджик конструкторы инфографика, бейджик конструкторы инфо, бейджик конструкторы инфо,бейджик конструкторы қағаз бейдждерінің конструкторы, йота бейдждерінің конструкторы, йос бейдждерінің конструкторы, бейдж конструкторы, бейдждердің конструкторы қалай жасауға болады, бейдждердің конструкторы канва, бейдждердің конструкторы сурет, бейдждердің конструкторы қалай пайдалану керек, бейдждердің конструкторы лайтрум, компьютердегі бейдждердің конструкторы, сайттағы бейдждердің конструкторы, македегі бейдждердің конструкторы, ағылшын тіліндегі бейдждердің конструкторы, бейдждердің конструкторы бағдарлама, бейдждердің конструкторы қосымша, бейдждердің конструкторы пдф, бейдждердің конструкторы редактор, бейдждердің конструкторы өлшемдер, бейдждердің конструкторы жүктеу, бейджик конструкторы сайт, бейджик конструкторы тильда, бейджик конструкторы таплинк, бейджик конструкторы мәтін, бейджиктер конструкторы қашықтан, бейджиктер конструкторы фотошоп, фигма бейджиктерінің конструкторы, хтмл бейджиктерінің конструкторы, түрлі-түсті бейджиктер конструкторы, бейджиктер конструкторы сызба, бейджиктер конструкторы шаблон, бейджиктер конструкторы 9 сынып, бейджиктер конструкторы 9 мамыр, бейджиктер конструкторы 9 әріп, оки бейджиктерінің конструкторы, окки бейджиктерінің конструкторы, оки бейджиктерінің конструкторы, окки бейджиктерінің конструкторы, okki бейджиктерінің конструкторы, тегін бейдждер конструкторы бейджик құрастырушы, бейджик жасау тегін, оки, окки, oki, okki, oky,okky, конструктор бейджиков оки, конструктор бейджиков окки",
        ru:"конструктор бейджиков, конструктор бейджиков онлайн, конструктор бейджиков автокад, конструктор бейджиков а4, конструктор бейджиков андроид, конструктор бережков, конструктор бейджиков бесплатно, конструктор бейджиков битрикс, конструктор бейджиков битрикс24, конструктор бейджиков без фона, конструктор бейджиков в ворде, конструктор бейджиков в word, конструктор бейджиков гугл, конструктор бейджиков гост, конструктор бейджиков для сайта, конструктор бейджиков для сотрудников, конструктор бейджиков для печати,конструктор бейджиков для фотошопа, конструктор бейджиков ексель, конструктор бейджиков егов, конструктор бейджиков ескд, конструктор бейджиков ёжики, конструктор бейджиков ёксель, конструктор бейджиков журнал, конструктор бейджиков жж, конструктор бейджиков женских, конструктор бейджиков журналов, конструктор бейджиков заказать, конструктор бейджиков заметки, конструктор бейджиков закон, конструктор бейджиков инструкция, конструктор бейджиков инфографика, конструктор бейджиков инфоурок, конструктор бейджиков инфо, конструктор бейджиков из бумаги, конструктор бейджиков йота, конструктор бейджиков йос, бейдж конструктор, конструктор бейджиков как сделать, конструктор бейджиков канва, конструктор бейджиков картинка, конструктор бейджиков как пользоваться, конструктор бейджиков лайтрум, конструктор бейджиков на компьютере, конструктор бейджиков на сайте, конструктор бейджиков на маке, конструктор бейджиков на английском, конструктор бейджиков программа, конструктор бейджиков приложение, конструктор бейджиков пдф, конструктор бейджиков редактор, конструктор бейджиков размеры, конструктор бейджиков скачать, конструктор бейджиков сайт, конструктор бейджиков тильда, конструктор бейджиков таплинк, конструктор бейджиков текст, конструктор бейджиков удаленно, конструктор бейджиков фотошоп, конструктор бейджиков фигма, конструктор бейджиков хтмл, конструктор бейджиков цветные, конструктор бейджиков чертежник, конструктор бейджиков шаблон, конструктор бейджиков 9 класс, конструктор бейджиков 9 мая, конструктор бейджиков 9 букв, конструктор бейджиков оки, конструктор бейджиков окки, конструктор бейджиков oki, конструктор бейджиков okki, бесплатный конструктор бейджиков, бесплатно сделать бейджик, оки, окки, oki, okki, oky, okky, конструктор бейджиков оки, конструктор бейджиков окки",
        en:"badge constructor, badge constructor online, badge constructor autocad, badge constructor a4, badge constructor android, badge constructor berezhkov, badge constructor for free, badge constructor bitrix, badge constructor bitrix24, badge constructor without background, badge constructor in word, badge constructor in word, badge constructor google, badge constructor gost, badge constructor for website, badge constructor for employees, badge constructor for printing,badge constructor for photoshop, badge constructor excel, the constructor of badges egov, the constructor of badges eskd, the constructor of badges hedgehogs, the constructor of badges excel, the constructor of badges magazine, the constructor of badges lj, the constructor of badges women, the constructor of badges magazines, the constructor of badges order, the constructor of badges notes, the constructor of badges law, the constructor of badges instruction, the constructor of badges infographics, the constructor of badges infowork, the constructor of badges info, constructor of paper badges, constructor of iota badges, constructor of yos badges, badge constructor, badge constructor how to make, the constructor of badges canvas, the constructor of badges picture, the constructor of badges how to use, the constructor of badges lightrum, the constructor of badges on the computer, the constructor of badges on the website, the constructor of badges on the mac, the constructor of badges in English, the constructor of badges program, the constructor of badges application, the constructor of badges pdf, the constructor of badges editor, the constructor of badges sizes, the constructor of badges download, badge constructor website, badge constructor tilda, badge constructor taplink, badge constructor text, the constructor of badges remotely, the constructor of badges photoshop, the constructor of badges figma, the constructor of badges html, the constructor of badges color, the constructor of badges draftsman, the constructor of badges template, the constructor of badges grade 9, the constructor of badges may 9, the constructor of badges 9 letters, the constructor of badges oki, the constructor of badges okki, the constructor of badges okki, the constructor of badges okki, free badge constructor, free to make a badge, oki, okki, oky, okky, constructor badge oki, constructor badge okki, constructor badge oky, constructor badge okky"
    }
}