export default {
    title:{
        kk:"Депозит",
        ru:"Депозит",
        en:"Deposit"
    },
    description:{
        kk:"Мен депозитпен қанша ақша жинай аламын?",
        ru:"Сколько я накоплю с Депозитом?",
        en:"How much will I save with a Deposit?"
    },
    jan:{
        kk:"Қаңт.",
        ru:"Янв.",
        en:"Jan."
    },
    feb:{
        kk:"Ақп.",
        ru:"Фев.",
        en:"Feb."
    },
    march:{
        kk:"Нау.",
        ru:"Март",
        en:"March"
    },
    april:{
        kk:"Сәу.",
        ru:"Апр.",
        en:"Apr."
    },
    may:{
        kk:"Мам.",
        ru:"Май",
        en:"May"
    },
    june:{
        kk:"Мау.",
        ru:"Июнь",
        en:"June"
    },
    july:{
        kk:"Шіл.",
        ru:"Июль",
        en:"July"
    },
    aug:{
        kk:"Там.",
        ru:"Авг.",
        en:"Aug."
    },
    sep:{
        kk:"Қыр.",
        ru:"Сен.",
        en:"Sep."
    },
    oct:{
        kk:"Қаз.",
        ru:"Окт.",
        en:"Oct."
    },
    nov:{
        kk:"Қар.",
        ru:"Ноя.",
        en:"Nov."
    },
    dec:{
        kk:"Жел.",
        ru:"Дек.",
        en:"Dec."
    },
}